name: Sync Sales Sheet to Kesion

on:
  workflow_dispatch: {}  # Manual trigger
  # Triggered by child repo when main branch is updated

jobs:
  sync-sales-sheet:
    runs-on: ubuntu-latest
    concurrency:
      group: sync-sales-sheet
      cancel-in-progress: false
    
    env:
      PARENT_REPO: https://github.com/novatrade-co-jp/proj-kesion-backend-novatrade
      PARENT_BRANCH: develop  # Base branch for new sync branch
      CHILD_REPO: https://github.com/panhouse/prj-kesion-sales-sheet  # sales-sheet repo
      CHILD_BRANCH: main  # sales-sheet main branch
      CHILD_MODULE_PATH: .  # Root of sales-sheet repo
      PARENT_MODULE_PATH: apps/sales_sheet  # Target path in kesion
      TIMESTAMP: ${{ format('YYYY-MM-DD-HH-mm-ss', 'now') }}

    steps:
      - name: Checkout kesion repo (develop branch)
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PARENT_BRANCH }}
          fetch-depth: 0

      - name: Create sync branch 
        run: |
          BRANCH_NAME="panhouse-sales-sheet-${{ env.TIMESTAMP }}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b "$BRANCH_NAME"
          echo "Created branch: $BRANCH_NAME"

      - name: Checkout sales-sheet repo
        uses: actions/checkout@v4
        with:
          repository: panhouse/prj-kesion-sales-sheet
          ref: ${{ env.CHILD_BRANCH }}
          path: sales-sheet
          token: ${{ secrets.SALES_SHEET_TOKEN }}  # PAT with access to sales-sheet repo
          fetch-depth: 0

      - name: Sync sales-sheet -> kesion/apps/sales_sheet
        run: |
          # Create target directory
          mkdir -p "${{ env.PARENT_MODULE_PATH }}"
          
          # Remove existing content
          rm -rf "${{ env.PARENT_MODULE_PATH }}"/*
          
          # Copy all files from sales-sheet repo
          cp -r sales-sheet/* "${{ env.PARENT_MODULE_PATH }}/"
          
          # Remove .git directory if it exists
          rm -rf "${{ env.PARENT_MODULE_PATH }}/.git"
          
          # Remove any other unnecessary files
          rm -rf "${{ env.PARENT_MODULE_PATH }}/.github"
          rm -rf "${{ env.PARENT_MODULE_PATH }}/.gitignore"
          rm -rf "${{ env.PARENT_MODULE_PATH }}/.gitattributes"
          
          echo "Synced sales-sheet content to ${{ env.PARENT_MODULE_PATH }}"

      - name: Check for changes
        id: check-changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected, will create PR"
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      - name: Commit changes
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${{ env.PARENT_MODULE_PATH }}"
          git commit -m "Sync sales-sheet from ${{ env.CHILD_REPO }} @ ${{ github.sha }}

          - Source: ${{ env.CHILD_REPO }}@${{ env.CHILD_BRANCH }}
          - Target: ${{ env.PARENT_MODULE_PATH }}
          - Timestamp: ${{ env.TIMESTAMP }}
          - Triggered by: ${{ github.event_name }}"

      - name: Push sync branch
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          git push origin "${{ env.BRANCH_NAME }}"
          echo "Pushed branch: ${{ env.BRANCH_NAME }}"

      - name: Create Pull Request
        if: steps.check-changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync sales-sheet from ${{ env.CHILD_REPO }} @ ${{ github.sha }}"
          branch: "${{ env.BRANCH_NAME }}"
          base: ${{ env.PARENT_BRANCH }}
          title: "Sync sales-sheet from ${{ env.CHILD_REPO }} - ${{ env.TIMESTAMP }}"
          body: |
            ## Automated Sync of Sales Sheet
            
            This PR syncs the latest changes from the **sales-sheet** repository to the **kesion** repository.
            
            ### Details
            - **Source**: `${{ env.CHILD_REPO }}@${{ env.CHILD_BRANCH }}`
            - **Target**: `${{ env.PARENT_MODULE_PATH }}`
            - **Sync Time**: `${{ env.TIMESTAMP }}`
            - **Trigger**: `${{ github.event_name }}`
            
            ### What Changed
            - Updated `${{ env.PARENT_MODULE_PATH }}/` directory with latest sales-sheet content
            - All files from sales-sheet repo have been synchronized
            
            ### Review Notes
            - This is an automated sync - please review the changes
            - The sync preserves the structure and content from the source repository
            - Any conflicts should be resolved manually if they occur
            
            ---
            *This PR was automatically generated by GitHub Actions*
          labels: |
            automated
            sync
            sales-sheet
          assignees: |
            ${{ github.repository_owner }}
          reviewers: |
            ${{ github.repository_owner }}

      - name: Cleanup on no changes
        if: steps.check-changes.outputs.has_changes == 'false'
        run: |
          echo "No changes to sync. Skipping PR creation."
          # Delete the branch if no changes
          git push origin --delete "${{ env.BRANCH_NAME }}" || true
